name: Deploy

on:
  push:
    branches: [main]

defaults: # run from .
  run:
    working-directory: .

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # checkout the code from my repository
        uses: actions/checkout@v4

      - name: Set up Java 17 # set up the Java 17 environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/whattheburger:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/whattheburger:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export IMAGE_TAG=${{ github.sha }}
            
            docker compose pull backend
            docker compose up -d backend
            
            echo "Waiting for application startup..."
            
            for i in {1..30} do
              if curl -fsS http://localhost:8080/actuator/health; then
                echo "Health check passed"
                exit 0
              fi
              
              echo "Waiting... ($i/30)"
              sleep 5
            done
            
            echo "Health check failed"
            docker compose logs backend --tail=100
            exit 1